import test from 'node:test';import assert from 'node:assert/strict';
import {GameEngine} from './engine.mjs';
import {emptyProfile,migrateProfile,SkillSession,practiceWords,unlockAchievements,career}from './skill-model.mjs';
import {dailyChallenge,bossLevels,seededRandom,shareResult}from './missions.mjs';
test('daily challenge is deterministic in UTC and isolates its random stream',()=>{const a=dailyChallenge(new Date('2026-10-05T00:01Z'),'pt'),b=dailyChallenge(new Date('2026-10-05T23:59Z'),'pt');assert.deepEqual(a.words,b.words);assert.equal(a.seed,b.seed);assert.equal(a.random(),b.random());assert.notEqual(a.seed,dailyChallenge(new Date('2026-10-06T00:00Z')).seed);});
test('skill records actual keys, bounded latency, errors and corrections',()=>{const p=emptyProfile(),s=new SkillSession({profile:p});s.record({typed:'r',expected:'r',correct:true,time:0,wordId:1});s.record({typed:'t',expected:'e',correct:false,time:180,wordId:1});s.record({typed:'e',expected:'e',correct:true,time:360,wordId:1});s.correction();const r=s.finish({seconds:60,combo:2});assert.equal(r.accuracy,200/3);assert.equal(r.corrections,1);assert.equal(p.keys.e.errors,1);assert.equal(p.confusions['e→t'].errors,1);assert.equal(r.wpm,.4);assert.equal(r.rawWpm,.6);assert.equal(p.keys.e.samples,2);});
test('pressure changes gradually, supports fixed challenge and mobile allowance',()=>{const s=new SkillSession();for(let i=0;i<25;i++)s.record({typed:'x',expected:'a',correct:false,time:i*200,wordId:1});assert.ok(s.pressure(1,.1)<1&&s.pressure(1,.1)>.99);assert.equal(s.pressure(.8,1,{fixed:true}),1);assert.ok(s.pressure(1,1,{mobile:true})<1);});
test('spaced practice is sparse and ignores patterns not yet due',()=>{const p=emptyProfile();p.patterns.er={attempts:8,errors:5,due:1000};const words=['error','coffee','report','printer'];assert.deepEqual(practiceWords(words,p,500),words);assert.equal(practiceWords(words,p,1500).length,5);});
test('profile migration handles corrupt values without deleting legacy data',()=>{assert.equal(migrateProfile({version:9}).version,2);const p=migrateProfile({version:1,sessions:[{wpm:45,accuracy:98,seconds:60},{wpm:NaN}],keys:{a:{attempts:10,errors:2}},achievements:['flow','flow']});assert.equal(p.sessions.length,1);assert.equal(p.keys.a.attempts,10);assert.deepEqual(p.achievements,['flow']);});
test('achievements are earned once and career uses measured proficiency',()=>{const p=emptyProfile();p.perfectLevels=1;assert.equal(unlockAchievements(p).length,1);assert.equal(unlockAchievements(p).length,0);p.sessions=[{correct:300,wpm:62,accuracy:96,combo:50,seconds:60}];assert.equal(career(p).rank,3);});
test('time limited runs finish on active clock, pausing does not consume duration',()=>{const g=new GameEngine({sessionSeconds:1}).start();g.pause();g.tick(.1);assert.equal(g.elapsed,0);g.resume();for(let i=0;i<11;i++)g.tick(.1);assert.equal(g.status,'won');assert.ok(g.drainEvents().some(e=>e.type==='victory'));});
test('boss phases change simultaneous threat rules and preserve exact punctuation',()=>{const levels=bossLevels('pt',true),g=new GameEngine({campaignLevels:levels,officeTactics:true,advanced:true,mode:'reading'}).start();assert.equal(g.boss.id,'printer');assert.equal(g._maxEnemies,1);assert.equal(levels.length,9);assert.match(levels[2].text,/[!:]/);g.wave=5;assert.equal(g.boss.id,'meeting');assert.equal(g._maxEnemies,4);});
test('reply all actually emits extra threats, deadline accelerates, defaults remain stable',()=>{const g=new GameEngine({officeTactics:true,random:seededRandom(2),customText:'mail reply report'}).start();g.enemies[0].archetype='reply';for(const c of g.enemies[0].word)g.typeChar(c);assert.equal(g.enemies.length,2);const ordinary=new GameEngine().start();assert.equal(ordinary.enemies[0].archetype,null);});
test('new engine options survive an old-compatible snapshot',()=>{const g=new GameEngine({officeTactics:true,mobile:true,sessionSeconds:120}).start();g.pressure=.8;const restored=GameEngine.fromSnapshot(g.snapshot());assert.equal(restored.pressure,.8);assert.equal(restored.officeTactics,true);assert.equal(restored.sessionSeconds,120);});
test('sharing includes challenge identity and meaningful metrics',()=>{assert.match(shareResult({mode:'daily',wpm:50,accuracy:98,combo:40,score:1200},{day:'2026-10-05'}),/DAILY 2026-10-05 · EN/);});

test('training cannot lose lives even when multiple targets escape together',()=>{const g=new GameEngine({training:true,mode:'reading',customText:'coffee report meeting'}).start();g._spawnEnemy();g._spawnEnemy();g.enemies.forEach(e=>e.y=.9999);g.tick(.1);assert.equal(g.status,'playing');assert.equal(g.lives,3);assert.equal(GameEngine.fromSnapshot(g.snapshot()).training,true);});
test('all boss phases are playable through final victory with finite spawn positions',()=>{const g=new GameEngine({campaignLevels:bossLevels('en',true),officeTactics:true,advanced:true,mode:'reading'}).start();let completed=0;for(let i=0;i<2000&&g.status!=='won';i++){if(g.status==='transition'){completed++;g.nextLevel();}for(const e of [...g.enemies]){assert.ok(Number.isFinite(e.x));for(const c of e.word.slice(e.progress))g.typeChar(c);}g.tick(.1);}assert.equal(g.status,'won');assert.equal(completed,8);assert.equal(g.kills,60);});
test('the meeting can fill all reserved lanes without invalid positions',()=>{const g=new GameEngine({campaignLevels:bossLevels(),officeTactics:true}).start();g.wave=6;g.enemies=[];g._customWords=g._levels[5].words;g._customIndex=0;for(let i=0;i<5;i++)g._spawnEnemy();assert.equal(g.enemies.length,5);assert.ok(g.enemies.every(e=>Number.isFinite(e.x)&&e.x<.7));});
