import {career,ACHIEVEMENTS}from './skill-model.mjs?v=20261005b';
import {t}from './locale.mjs?v=20261005b';
const make=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
export function drawTrend(canvas,sessions){const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;c.clearRect(0,0,w,h);const rows=sessions.slice(-20);if(!rows.length)return;c.strokeStyle='#47574f';for(let i=1;i<4;i++){c.beginPath();c.moveTo(0,i*h/4);c.lineTo(w,i*h/4);c.stroke();}const max=Math.max(80,...rows.map(s=>s.wpm));for(const [field,color,scale]of [['wpm','#eac681',max],['accuracy','#8dddd6',100]]){c.strokeStyle=color;c.lineWidth=3;c.beginPath();rows.forEach((s,i)=>{const x=8+i*(w-16)/Math.max(1,rows.length-1),y=h-8-s[field]/scale*(h-16);i?c.lineTo(x,y):c.moveTo(x,y);});c.stroke();}}
export function renderProfile(profile){
 const rank=career(profile);document.getElementById('careerTitle').textContent=t(rank.title);document.getElementById('careerNext').textContent=t(rank.next);
 const root=document.getElementById('profileContent');root.replaceChildren();
 root.append(make('p',t(rank.title),'profile-rank'));const summary=make('div',undefined,'profile-summary');
 for(const [label,value]of [['Partidas',profile.sessions.length],['Melhor WPM',Math.round(rank.bestWpm)],['Tempo de jogo',`${Math.round(profile.sessions.reduce((n,s)=>n+s.seconds,0)/60)} min`],['Troféus',profile.trophies.length]]){const card=make('div');card.append(make('strong',value),make('span',t(label)));summary.append(card);}root.append(summary);
 root.append(make('h3',t('Velocidade e precisão')));const chart=make('canvas');chart.width=500;chart.height=130;chart.setAttribute('role','img');chart.setAttribute('aria-label',t('Histórico de WPM e precisão'));root.append(chart);drawTrend(chart,profile.sessions);root.append(make('p','WPM · '+t('Precisão'),'chart-legend'));
 root.append(make('h3',t('Sinais do teclado')));const heat=make('div',undefined,'key-heatmap');for(const letter of 'QWERTYUIOPASDFGHJKLZXCVBNM0123456789.,;:!?'){const matches=Object.entries(profile.keys).filter(([k])=>k.toUpperCase()===letter);const attempts=matches.reduce((n,[,s])=>n+s.attempts,0),errors=matches.reduce((n,[,s])=>n+s.errors,0),rate=attempts?Math.round(100*(1-errors/attempts)):null;const key=make('span',letter,'key-cell');key.style.setProperty('--error',attempts?errors/attempts:0);key.append(make('small',rate===null?'—':rate+'%'));key.title=`${letter}: ${attempts} ${t('tentativas')}, ${errors} ${t('erros')}`;heat.append(key);}root.append(heat);
 const weak=Object.entries(profile.keys).filter(([,s])=>s.attempts>=3&&s.errors>0).sort((a,b)=>b[1].errors/b[1].attempts-a[1].errors/a[1].attempts).slice(0,4);root.append(make('p',t('A praticar')+': '+(weak.map(([key])=>key).join(' · ')||'—')));
 const slow=Object.entries(profile.keys).filter(([,s])=>s.samples>=3).sort((a,b)=>b[1].latency/b[1].samples-a[1].latency/a[1].samples).slice(0,4);root.append(make('p',t('Latência por tecla')+': '+(slow.map(([key,s])=>`${key} ${Math.round(s.latency/s.samples)} ms`).join(' · ')||'—')));
 const confused=Object.entries(profile.confusions).sort((a,b)=>b[1].errors-a[1].errors).slice(0,3);root.append(make('p',t('Confusões frequentes')+': '+(confused.map(([key,s])=>`${key} (${s.errors})`).join(' · ')||'—')));
 const patterns=Object.entries(profile.patterns).filter(([,s])=>s.attempts>=3&&s.errors>0).sort((a,b)=>b[1].errors/b[1].attempts-a[1].errors/a[1].attempts).slice(0,3);root.append(make('p',t('Combinações a praticar')+': '+(patterns.map(([key])=>key).join(' · ')||'—')));
 root.append(make('h3',t('Conquistas')));const trophies=make('div',undefined,'achievement-grid');for(const a of ACHIEVEMENTS){const item=make('div',t(a.name),profile.achievements.includes(a.id)?'earned':'locked');item.prepend(make('span',profile.achievements.includes(a.id)?'✦ ':'◇ '));trophies.append(item);}root.append(trophies);
 root.append(make('h3',t('Últimas partidas')));const list=make('ol');for(const s of profile.sessions.slice(-5).reverse())list.append(make('li',`${new Date(s.date).toLocaleDateString()} · ${Math.round(s.wpm)} WPM · ${s.accuracy.toFixed(1)}% · ${s.combo} ${t('Combo')}`));root.append(list);
}
export function renderRunResult(result,profile,newAchievements){const el=document.getElementById('skillResult');const weak=Object.entries(profile.keys).filter(([,s])=>s.attempts>=3&&s.errors>0).sort((a,b)=>b[1].errors/b[1].attempts-a[1].errors/a[1].attempts).slice(0,3).map(([key])=>key);const strong=Object.entries(profile.keys).filter(([,s])=>s.attempts>=5&&s.errors===0).slice(0,5).map(([key])=>key);const feedback=weak.length?t('O próximo treino vai reintroduzir estes sinais com calma.'):t('Mantém a precisão; a velocidade vem com o ritmo.');
 el.replaceChildren(make('p',`${t('Combo')}: ${result.combo} · ${t('Correções')}: ${result.corrections}`),make('p',`${t('WPM bruto')}: ${Math.round(result.rawWpm)} · ${t('Evolução')}: ${result.delta===null?'—':(result.delta>=0?'+':'')+result.delta.toFixed(1)} WPM`),make('p',`${t('A praticar')}: ${weak.join(' · ')||'—'} · ${t('Teclas fortes')}: ${strong.join(' · ')||'—'}`),make('p',feedback,'result-advice'));
 if(result.reactionMs!==null)el.append(make('p',t('Primeira tecla após o alvo')+': '+Math.round(result.reactionMs)+' ms'));
 if(newAchievements.length)el.append(make('p','✦ '+newAchievements.map(a=>t(a.name)).join(' · '),'earned'));
 el.append(make('p',t(career(profile).next)));
}
export function downloadResult(result,identity){
 const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=700;const c=canvas.getContext('2d');c.fillStyle='#152921';c.fillRect(0,0,1000,700);c.strokeStyle='#d5b67e';c.lineWidth=2;c.strokeRect(38,38,924,624);c.fillStyle='#ece6d2';c.font='bold 56px monospace';c.fillText('BORING OFFICE',78,120);c.font='italic 24px Georgia';c.fillStyle='#c6baa0';c.fillText('by Ivan Gomes',80,158);c.font='24px monospace';c.fillText(identity,80,223);c.font='bold 110px monospace';c.fillStyle='#e9be76';c.fillText(`${Math.round(result.wpm)} WPM`,78,374);c.font='36px monospace';c.fillStyle='#8edace';c.fillText(`${result.accuracy.toFixed(1)}% ACC · COMBO ${result.combo}`,80,462);c.fillStyle='#d4dacf';c.fillText(`${result.score} PTS`,80,522);c.font='20px monospace';c.fillText('scalifornia.github.io/orbita-web',80,605);let dialog=document.getElementById('resultCardDialog');if(!dialog){dialog=make('dialog');dialog.id='resultCardDialog';dialog.className='result-card-dialog';document.body.append(dialog);}else dialog.replaceChildren();const image=make('img');image.alt='Boring Office · '+identity;image.src=canvas.toDataURL('image/png');const link=make('a',t('Guardar imagem'),'primary-button');link.href=image.src;link.download='boring-office-result.png';const close=make('button',t('Fechar'),'custom-button');close.addEventListener('click',()=>dialog.close());dialog.append(image,make('p',t('Guarda o cartão ou mantém a imagem premida no telemóvel.')),link,close);dialog.showModal();
}
