// Original retellings of traditional Aesop fables, in two languages.
export const stories = {
  hare: {
    pt: { title: 'A Lebre e a Tartaruga', text: 'Uma lebre ria da tartaruga: "És tão lenta!" A tartaruga respondeu: "Vamos fazer uma corrida?" A lebre aceitou. Quando a raposa deu o sinal, as duas partiram. A lebre correu até à colina e olhou para trás. A tartaruga ainda estava longe. "Tenho tempo para descansar", pensou. Deitou-se à sombra de uma árvore e adormeceu. A tartaruga continuou, passo a passo, sem parar. O sol subiu; o caminho parecia não ter fim. Mesmo cansada, ela avançou. Quando a lebre acordou, viu a rival perto da meta. Correu com toda a força, mas chegou tarde: a tartaruga já tinha vencido! "Como conseguiste?", perguntou. "Continuei a andar." A lebre aprendeu a respeitar os outros. A pressa e o orgulho não substituem a persistência.' },
    en: { title: 'The Hare and the Tortoise', text: 'A hare laughed at a tortoise: "You are so slow!" The tortoise replied: "Shall we have a race?" The hare agreed. When the fox gave the signal, they set off. The hare ran to the hill and looked back. The tortoise was still far away. "I have time to rest", he thought. He lay beneath a tree and fell asleep. The tortoise continued, step by step, without stopping. The sun rose; the road seemed endless. Although tired, she kept going. When the hare woke up, he saw his rival near the finish. He ran as fast as he could, but he was too late: the tortoise had already won! "How did you do it?", he asked. "I kept walking." The hare learned to respect others. Speed and pride cannot replace perseverance.' }
  },
  lion: {
    pt: { title: 'O Leão e o Rato', text: 'Um leão dormia na floresta quando um rato passou sobre a sua pata. O leão acordou e prendeu o pequeno visitante. "Por favor, deixa-me ir! Um dia poderei ajudar-te." O leão riu: "Tu? Como poderias ajudar alguém tão forte?" Mesmo assim, soltou o rato. Dias depois, o leão ficou preso numa rede. Puxou as cordas, rugiu e tentou fugir; nada resultou. O rato ouviu o rugido e correu até lá. "Não tenhas medo: vou libertar-te!" Com os seus dentes, roeu uma corda, depois outra. Pouco a pouco, abriu um buraco na rede. O leão saiu e agradeceu ao amigo. "Eu estava enganado", admitiu. "A tua ajuda foi enorme!" Desde então, nunca desprezou os pequenos. Um gesto de bondade pode criar uma amizade; todos têm algo para oferecer.' },
    en: { title: 'The Lion and the Mouse', text: 'A lion was sleeping in the forest when a mouse ran over his paw. The lion woke up and caught the tiny visitor. "Please let me go! One day I may help you." The lion laughed: "You? How could you help someone so strong?" Even so, he freed the mouse. Days later, the lion became trapped in a net. He pulled the ropes, roared and tried to escape; nothing worked. The mouse heard him and hurried over. "Do not be afraid: I will set you free!" With his teeth, he chewed through one rope, then another. Little by little, he made a hole in the net. The lion stepped out and thanked his friend. "I was wrong", he admitted. "Your help was wonderful!" From then on, he never looked down on small creatures. An act of kindness can begin a friendship; everyone has something to offer.' }
  }
};
